name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.9.0
        with:
          elixir-version: 1.12.3
          otp-version: 22.3.4

      - name: Install Dependencies
        run: mix deps.get

      - name: Setup Database
        run: mix do ecto.create, ecto.migrate

      - name: Run Tests
        run: mix test
